# Generated by Django 3.2.7 on 2021-09-06 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_finalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, unique=True)),
                ('pwd', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
