# Generated by Django 3.2.7 on 2021-09-06 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_finalapp', '0002_log'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='log',
            table='Logs',
        ),
    ]
