# Generated by Django 3.2.7 on 2021-09-06 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_finalapp', '0003_alter_log_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blog_post',
            table='Blog_post',
        ),
    ]
