# Generated by Django 3.2.7 on 2021-09-06 07:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog_finalapp', '0005_blog_post_is_primary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_post',
            name='is_primary',
        ),
        migrations.AddField(
            model_name='blog_post',
            name='likes',
            field=models.ManyToManyField(related_name='blog_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
